### ISSUE TITLE
Case in custom slot types

### ISSUE THREAD

**Issue by vinczente** [johnwheeler/flask-ask#100]
Hi there,

In Alexa's responses the case of custom slots types is not followed
Not sure if there is anything that can be done... as its probably a Amazon issue

**Comment by johnwheeler** [comment]
This is too vague to operate on. Can you please provide more information and some sample code that illustrates the issue?

Thanks

**Comment by vinczente** [comment]
Hi John,
Sorry if my explanation was not helpful.
if I create a custom slot type, ie:

COLORS
Red
Blue
Green

if somebody say "My favorite color is green" matching "My favorite color is {color}"
flask ask will receive "green" instead of "Green" for the color argument

Hope that make more sense?

**Comment by treethought** [comment]
This may not fix what your describing, since you're talking about the case of the actual value being passed, but you can map a function argument to a slot name with the action decorator's ``mapping`` parameter.

```
@ask.action('favorite-color', mapping={'color': 'Color'}) 
def echo_color(color):
    return statement('Your color is {}'.format(color))
```

For the case of the actual value, you should be able to determine that with how you define your custom slots. So,

COLORS
red
blue
green
