### ISSUE TITLE
Open Ticket with AMAZON.NUMBER

### ISSUE THREAD

**Issue by jersonjunior** [johnwheeler/flask-ask#106]
I have the following doubt, it is possible to pass numbers to a stream using AMAZON.NUMBER using Flask-Ask.

For example.
Me: "Open a new ticket
Alexa: "Please, speak the 4 digits of your license plate and wait"

Then I need to store in a variable these 4 digits and pass it on to a Webservice Rest to identify the login name of the client, email and phone.

Me: "I'm having problems printing"
Alexa: Do you want a new print request? Yes or no.

Me: Yes
Alexa: Your request has been successfully registered!

**Comment by johnwheeler** [comment]
If their are always four digits, use AMAZON.FOUR_DIGIT_NUMBER

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/slot-type-reference#four_digit_number

Otherwise, you can create muliple utterances that chain utterances together


{number}, {number}, and {number}

{number}, {number}, {number}, and {number}

{number}, {number}, {number}, {number}, and {number}

**Comment by jersonjunior** [comment]
I have a question, I need an intention for each user on my system or I can review what the user said to Alexa, for example:

ID of Jerson is 1801
Bruno's ID is 1933

Please, speak the 4 digits of your license plate and wait"

var id=1801

**Comment by johnwheeler** [comment]
These questions are really outside the scope of Flask-Ask, but you should use AMAZON.US_FIRST_NAME (or your specific locale if it provides one)

**Comment by jersonjunior** [comment]
OK. Through the 4 digits that I can find the user login, would it be possible to pass the 4 digits to a variable in python and then question what it wants? Would I have to create intentions for each user number or is it possible to go over the 4 unintentional digits?
