### ISSUE TITLE
play sound from mp3 url in file.yaml

### ISSUE THREAD

**Issue by shaolinkhoa** [johnwheeler/flask-ask#123]
Hi,
I tried sample project [tidepooler](https://github.com/johnwheeler/flask-ask/tree/master/samples/tidepooler) and heard Alexa play OceanWaves sound when it was launched.
I changed another mp3 url but it didn't work.

Does Alexa only play the mp3 url which is from `**s3.amazonaws.com**` ?

**Comment by voutilad** [comment]
Amazon does have some requirements for audio files. The documentation for the [AudioPlayer interface](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/custom-audioplayer-interface-reference#play) mentions the following:

> The audio file must be hosted at an Internet-accessible HTTPS endpoint. HTTPS is required, and the domain hosting the files must present a valid, trusted SSL certificate. Self-signed certificates cannot be used. Many content hosting services provide this. For example, you could host your files at a service such as Amazon Simple Storage Service (Amazon S3) (an Amazon Web Services offering).
>
>The supported formats for the audio file include AAC/MP4, MP3, HLS, PLS and M3U. Bitrates: 16kbps to 384 kbps.

I believe there may be another caveat that the hosting endpoint must support CORS for requests from `http://ask-ifr-download.s3.amazonaws.com` per the [skill card documentation](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/providing-home-cards-for-the-amazon-alexa-app#image_hosting)

It's not always clear in the documentation, but I've found HTTPS and CORS tend to be a requirement for any media Amazon is going to present to the user either as part of the card or audio. Using S3 doesn't always automatically suffice as you may need to still enable CORS per the skill card doc linked above.

Can you try the above suggestions and let us know?

**Comment by shaolinkhoa** [comment]
I'm sorry. I really don't understand about CORS. 
But I just found this [tutorial](http://www.apcp.biz/single-post/2016/02/05/Adding-MP3-Sound-to-Your-Alexa-Skill) . I will try this

**Comment by voutilad** [comment]
Did HTTPS resolve your issue, @shaolinkhoa?

**Comment by shaolinkhoa** [comment]
My lab has banned: Google drive, media fire, etc . So I still can't find web site to upload file mp3.  
I also tried [audio sample folder projects](https://github.com/johnwheeler/flask-ask/tree/master/samples/audio) but Alexa didn't play any sound even though those link can run normally on my browser.
Can you check it .

**Comment by johnwheeler** [comment]
This is working normally. You need to find an HTTPS server to upload to.

**Comment by shaolinkhoa** [comment]
@johnwheeler ,
I uploaded the song to amazon S3 and then the mp3 url is able to play on file.yaml.
But when I copied the mp3 url to  [audio sample folder projects](https://github.com/johnwheeler/flask-ask/tree/master/samples/audio). It didn't play any sound ?
this is my mp3 url:
`https://s3.amazonaws.com/tma.dc4.sensor/alexa.sound.khoa/song2.mp3`
What I did:
I upload flask-ask python project to` pythonanywhere.com` and run on it
I run my alexa on my linux pc.
I choose begin demo or play a sax ,but I can't hear anything

**Comment by voutilad** [comment]
If I understand correctly, @shaolinkhoa, you are:
* Hosting the audio file within your Flask application
* Trying to use SSML to play the file in a spoken response.

This should be possible today from my understanding and isn't so much a bug as just a use of Flask (and possible feature enhancement for Flask-Ask). Today, you'd need to do something like the following if you plan on hosting the audio file within the Flask application:

1. Use the [static files](http://flask.pocoo.org/docs/0.12/quickstart/#static-files) capability of Flask to properly expose the file via the web app.
2. Construct a valid url to the static file for substitution into the Alexa response. See the `url_for()` example in the previous link or the doc for [url_for()](http://flask.pocoo.org/docs/0.12/api/#flask.url_for)
3. Host your Flask app with HTTPS and an SSL certificate meeting Amazon's guidance for hosted media I shared previously (https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/providing-home-cards-for-the-amazon-alexa-app#image_hosting).
4. You still might need to enable CORS as instructed by Amazon. You can try without, but I'm not sure which parts of the Amazon infrastructure will be making the request for you audio file. For example, for images I believe the Alexa web and mobile apps themselves fetch the files for rendering in cards, so that might be why they require CORS.

**Comment by shaolinkhoa** [comment]
@voutilad 
Thank you for taking the time to help me.

I'm really sorry for not writing clearly.
I found 2 problem:

1/ I couldn't use SSML to play the file in a spoken response like you said above. 
But I found the way deal with it. I upload my mp3 file to Amazon S3 and use it's url. That is my solution now

2/ `audio(speech).play(stream_url, offset=93000)` in  [audio sample folder projects](https://github.com/johnwheeler/flask-ask/tree/master/samples/audio) doesn't work. 
I tried `playlist_demo` and `simple_demo` . But it didn't play any sound ? 

So my question now is "why I can't hear any sound from  playlist_demo and simple_demo"
thank you

**Comment by treethought** [comment]
@shaolinkhoa Are you calling play() with an offset of 93000 ms? This means the stream will begin playback at 93 sec (1 min 33 sec).  I looked at the url you are using and the song is only 1 min 31 seconds long.

**Comment by shaolinkhoa** [comment]
Hi @treethought ,
I'm sorry. I really don't know how `play()`. I can't find tutorial about it on [Full online documentation](https://alexatutorial.com/flask-ask/).

What I did to test:

- I upload all the code of [ask_audio.py](https://github.com/johnwheeler/flask-ask/blob/master/samples/audio/simple_demo/ask_audio.py) to `pythonanywhere.com`
- I erased `offset=93000` like you said 
- I replace 2 mp3 url in ask_audio.py with my url:
`https://s3.amazonaws.com/tma.dc4.sensor/alexa.sound.khoa/song1.mp3`
`https://s3.amazonaws.com/tma.dc4.sensor/alexa.sound.khoa/song2.mp3`

But I still can't hear any sound

**Comment by voutilad** [comment]
@shaolinkhoa it looks like you still haven't enabled CORS on your S3 buckets.

Using http://test-cores.org it looks like I'm seeing CORS errors.

<img width="674" alt="screen shot 2017-04-27 at 16 48 31" src="https://cloud.githubusercontent.com/assets/9891346/25503737/64614d42-2b69-11e7-916d-4a504b949fb4.png">

For an example of an S3 file that has CORS set properly and works with Alexa, see: https://s3.amazonaws.com/www.vpr.net/apps/images/classical-logo.png 

Please try enabling CORS on your S3 bucket per the [Alexa docs](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/providing-home-cards-for-the-amazon-alexa-app#image_hosting). Additional docs for S3 and CORS are [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html#how-do-i-enable-cors).

Until you enable CORS and can see something like the below using http://test-cores.org and your mp3 url, your audio will not play via Alexa.

<img width="806" alt="screen shot 2017-04-27 at 16 47 37" src="https://cloud.githubusercontent.com/assets/9891346/25503701/4868fc84-2b69-11e7-8643-a6625775c725.png">

**Comment by neotheicebird** [comment]
@shaolinkhoa I think the issue is with the format of the mp3 files you have uploaded to s3. Alexa requires a specific type of mp3.

The mp3s need to be in MPEG Version 2, 48kbps bitrate, 16kHz sampling rate, and your mp3 need to be **under 90secs**, some of which are not met by your mp3s.

You can try ffmpeg/Audacity to convert the audio files to meet the specifications.

Ref: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/speech-synthesis-markup-language-ssml-reference#audio

**Comment by treethought** [comment]
@neotheicebird I believe those requirements only apply to embedding audio within ssml, not streaming audio via Audio Directives. 

@shaolinkhoa Are you sure you have enabled AudioPlayer when creating your skill in the Amazon Developer Console?

**Comment by neotheicebird** [comment]
@treethought That makes sense. Thanks.
