### ISSUE TITLE
Stopping audio stream

### ISSUE THREAD

**Issue by NightRang3r** [johnwheeler/flask-ask#133]
Hi,

I noticed that when you play an audio stream and you try to stop it while playing, (for example, Alexa, Stop), It will invoke the **AMAZON.PauseIntent** and not the **AMAZON.StopIntent**, I tested it with the flask-ask/samples/audio/simple_demo/ example, Instead of saying "stopping" it says "Paused the stream"

Anyone knows how to fix this?

Thanks!

**Comment by voutilad** [comment]
I believe this is just an oddity on the Amazon side. It shouldn't cause any problems as long as you implement both intents just in case. I found this confusing, too, since the user may say "stop" but Amazon is really trying to pause a stream so it can be resumed later.

To be honest, I'm not sure exactly what will generate an *AMAZON.StopIntent*. :-)

**Comment by NightRang3r** [comment]
I am wondering how will it work if your skill plays podcasts and reads rss feeds and you want to stop the rss feed reading, it will say pausing stream as well...

Thanks for the answer...

**Comment by voutilad** [comment]
You don't need to return a spoken statement when handling pause intents. In one of my projects, we [log the pausing behavior](https://github.com/vprnet/vpr-alexa-skill/blob/master/vpr_alexa/webapp.py#L124-L130) and don't generate any spoken response to the user.

**Comment by NightRang3r** [comment]
Great, Thanks!
