### ISSUE TITLE
Flask-Ask Python 3.6 Support?

### ISSUE THREAD

**Issue by s2tu** [johnwheeler/flask-ask#134]
Hello, 

I have written a Flask-Ask application and I am deploying it using Zappa.   When I run my tests with ngrok everything works fine.  However when I deploy using Zappa I get the following error while running my tests: 

`File "/var/task/models.py", line 4, in <module>
    from flask_ask import session
  File "/var/task/flask_ask/__init__.py", line 9, in <module>
    from .core import (
  File "/var/task/flask_ask/core.py", line 12, in <module>
    from . import verifier, logger
  File "/var/task/flask_ask/verifier.py", line 8, in <module>
    from OpenSSL import crypto
  File "/var/task/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/var/task/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/var/task/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/var/task/cryptography/hazmat/bindings/openssl/binding.py", line 12, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._openssl'`

I am using python 3.6 and my Flask-Ask version is 0.9.3.  Is there support for Python 3.6 ?

**Comment by voutilad** [comment]
Flask-Ask has works fine in Python 3.6 from my experience and I've hosted (and have clients hosting) apps in Heroku using that runtime version.

Chances are it's an environmental issue when you run in AWS Lambda (which is the purpose of Zappa if I'm not mistaken) since it needs to install dependencies. Double check your `requirements.txt` file or however you're having the AWS Lambda system setup your Python environment. 

You might wan to check if that Lambda instance is properly installing the foreign function interface module (`ffi`) per [this SO answer](https://raspberrypi.stackexchange.com/a/28189) to a related traceback. Maybe try adding `libffi-dev` to your `requirements.txt` since you won't have access to `apt`.

Ultimately Lambda is just using an underlying EC2 instance, so you could also spin up your own EC2 system using the base Amazon Linux AMI that Lambda runs your code on and make sure things work for you there. See http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

**Comment by voutilad** [comment]
@s2tu I was mistaken, sorry, it's been awhile since I used Lambda. Since with Lambda Amazon makes you package up all your dependencies, you need to make sure your package will run as-is inside their EC2 instance. I'd still recommend trying to create an instance using their AMI, make sure it works there, and follow their instructions for packaging and deploying a virtualenv.

If that still doesn't work, please let me know.

**Comment by johnwheeler** [comment]
It might be that when the crypto package was compiled for a zappa dependency called lambda-packages, that it was compiled for 2.7 only. 

https://github.com/Miserlou/lambda-packages/tree/master/lambda_packages

IIRC, I submitted the PR for that for that package when lambda only support 2.7

https://github.com/Miserlou/lambda-packages/pull/15

**Comment by voutilad** [comment]
@s2tu I'm going to close this for now as it sounds like an environmental issue.
