### ISSUE TITLE
Can you stop the request from the on_session_started callback?

### ISSUE THREAD

**Issue by rudf0rd** [johnwheeler/flask-ask#27]
Hey John,

Thanks for putting together a simple framework for the Alexa skills.  I knocked out my first skill, with account linking and external APIs in less than a day, largely in part to this.

One question i have and can't find any reference to in the docs is if it's possible to stop the entire request from continuing from the `on_session_started` callback?  What I'd like to is have it check if the account is linked once there, instead of at the top of every intent like I'm doing now.  I'm semi-new to python, so maybe I'm missing something basic here.

Thanks!

**Comment by johnwheeler** [comment]
Hi - 

The short answer is no, not currently.

on_session_started isn't part of the official Alexa Skills Kit API, and is a convenience method for doing things when a new session comes in. That can happen either during a launch intent, or any other intent when it's the first time the user is interacting with your skill.

You might consider creating your own decorator with functools.wrap and attaching it to all of your intents. otherwise, I'd need to create an on_intent callback, which I think it s good idea. Probably better to have before_intent and after_intent.

**Comment by rudf0rd** [comment]
That makes sense.  Thank you for the clarification!
