### ISSUE TITLE
Video on Zappa Deployment?

### ISSUE THREAD

**Issue by mastash3ff** [johnwheeler/flask-ask#35]
Would like to request a video referencing how to deploy a flask-ask via zappa.  I have not had any success following the README.md on zappa github or cannot find any references to assist in deploying to Lambda

**Comment by jksnetwork** [comment]
https://gun.io/blog/serverless-microservices-with-zappa-and-flask/

This tutorial helped me.  Went from never working with Alexa at all with little python experience to a working Alexa skill hosted on Lambda in about 4 hours.

The tutorial is aimed at flask in general and not flask-ask but the only real difference is the need to install the flask-ask package in your env when you install the other packages (i.e. pip install flask flask-ask zappa)

**Comment by relighted** [comment]
When setting up our found 4 issues that made it hard getting it running 
1: you Must setup the pip modules in a python  virtual environment so install virtualenv and define one for your project and switch to it,  then install the needful with ' pip install flask-ask zappa'.  Only run zappa when you have your venv active. 
2: using zappa and lambda it creates some resources,  but the names are limited in length because the deployment code adds very long strings.  Keep your name max 6 chars,  and your stage name 4. 
3 turned out I did not have the latest 2.7 python version,  and I needed to add a report source in my OS to upgrade 
4 issues with openssl,  I needed to update the OS and all packages else zappa had issues talking to api gw or lambda

Besides that,  I'm with jfk network above, my last simple skill was created, tested and published under 4 hours. The certification process has its own quirks, but manageable. 
Most annoying thing there is that I found that the keyword 'quit'  is part of the Amazon.NoIntent, which you have to implement else the certification team will not approve your skill.

**Comment by mastash3ff** [comment]
Thanks for the tips.  One things I'm confused on is the default handler entry that is suppose to be filled in on Lambda.  In several of the examples, I do not see any default handler.  What am I missing here?

**Comment by relighted** [comment]
For what its worth, The handler in Lambda for all my functions deployed with zappa is "handler.lambda_handler".

**Comment by krishnakt031990** [comment]
https://medium.com/@krishnateja_182/building-serverless-microservices-with-zappa-and-flask-to-make-alexa-skills-go-live-67d639297219#.r7lod34v0

**Comment by ohabash** [comment]
All ducumentation for this request is over my head.... For example: "set up your virtual environment"... I need to know more about that... I have built several Flask-Ask apps that i can run using ngrok endpoints but I want to deploy these. Is there anyone who can help with this. I most lack in AWS knowledge.

**Comment by relighted** [comment]
The zappa documentation is all you need to do but perhaps I can put it in context a bit. 

With zappa you deploy your flask-ask app to aws. It's fronted by the aws api gateway which proxies all requests to aws lambda.  This is needed because flask ask is an wgsi application and Alexa service doesn't speak that. So it needs a layer. zappa sets that all up for you. :) 

In order for lambda to run your code, it needs to be complete with dependencies and libraries. Zappa packages your code on deployment and uploads it all. For this reason all code /libs etc,  including zappa itself, needs to be installed in a python virtualenv with the app. A virtualenv is an isolated environment that ensures that the sw in it can only use that set of files in it and no system resources. 

0. your base system needs to have python, pip and virtualenv (Google on python virtualenv) 
1.switch to your flask-ask app folder. 
2.create a new virtualenv there
3.activate the virtualenv 
4.install flask-ask into this virtualenv with ' pip install flask-ask'
5.install zappa into this virtualenv with ' pip install zappa'
6. Configure your aws credentials on your environment (Google 'setup awssdk credentials'). Use an admin key pair at first,  create it in aws I'm service. 
7.run zappa init 
8.run zappa deploy
9.it should end without errors with an api gw URL that you need to use in your Alexa skill https configuration. 
--
Every time you do 'zappa update', you need to be in the activated virtualenv,  else zappa can't bundle up all files and links for lambda to run it. I just created a bash script so I never forget. 

Hope this helps.

**Comment by johnwheeler** [comment]
Here is a video tutorial I put together on how to deploy Flask-Ask skills to AWS Lambda with Zappa. Feedback appreciated

https://www.youtube.com/watch?v=mjWV4R2P4ks

**Comment by ohabash** [comment]
Perfect. Thank you
