### ISSUE TITLE
audio.resume() restarts song on playback

### ISSUE THREAD

**Issue by Danondso** [johnwheeler/flask-ask#71]
I've been working on this <a href="https://github.com/stevenleeg/geemusic"> repo </a> which is using the gmusicapi, whenever I've tried to resume playback the song keeps restarting from the beginning. I've stepped through the code and it looks like current_stream isn't having the offsetInMilliseconds set from the context (that's my thinking anyway). Is that something flask_ask handles someplace or is it something I have to set separately from the context?

**Comment by Danondso** [comment]
Is there anything else I can provide for this question to get answered? If there is please let me know.

**Comment by johnwheeler** [comment]
Hi Danondso, I'm not super familiar with how the streaming audio code works for Flask-Ask as I didn't write it.  This is something that would probably do well with the backend research done on your end with a P.R. Otherwise, you'd have to wait for another user with the same issue to come along and help in that capacity.

**Comment by Danondso** [comment]
Awesome I'll get started looking into it then.

**Comment by treethought** [comment]
Hey Danondso, I've been working on this issue and have fixed it so that the stream resumes from where it was paused. I'll try to clean up my work and push the change. I'm also trying to fix the offset issue - it is being correctly set from the on_playback_stopped requests, but I think it is overwritten by the PauseIntent. 
When you ask alexa to pause, flask-ask first receives an OnPlaybackStopped request (bc she pauses to listen to your command). Then immediately receives the Pause Intent, which seems to mess with the syncing of the current_stream.

**Comment by Danondso** [comment]
treethought that wold be super cool! That makes sense why I was seeing multiple requests go through in the debugger then.

**Comment by treethought** [comment]
Pausing/resuming with proper offsets should be working with the latest commit.

**Comment by m0ngr31** [comment]
Can you update the pip package for the new commits?

**Comment by johnwheeler** [comment]
Flask-Ask 0.8.4 has been uploaded

**Comment by Danondso** [comment]
Awesome I'll check this out when I get home. Thank you guys!

**Comment by m0ngr31** [comment]
That worked great. Thanks!

**Comment by mcverna** [comment]
It's working for me.  Thanks!
