### ISSUE TITLE
Missing system library?

### ISSUE THREAD

**Issue by jtslear** [johnwheeler/flask-ask#73]
Hello,

I'm working on trying python for the first time with Alexa utilizing AWS Lambda.  I'm not using Zappa for deployment, but another method of simply bundling up a zip file and rocking it out.  While this would normally work fine, once I add the `flask` and `flask_ask` dependencies, I can no longer run my function.

```
Unable to import module 'handler': libffi-72499c49.so.6.0.4: cannot open shared object file: No such file or directory
```

Being that `libffi` is required, how do you guys work around this?  Does Zappa do something special with this I'm unaware of?  From what I can tell, one is not able to modify the system that runs the actual function.  Which makes me ponder I'm doing something horribly wrong here.  My function is a copy and paste from the README.

**Comment by johnwheeler** [comment]
Yes - zappa depends on lambda-packages which includes libffi

https://github.com/Miserlou/lambda-packages/tree/master/lambda_packages

At any rate, you likely won't be able to use Flask-Ask without zappa on Lambda because Flask-Ask depends on Flask which depends on WSGI. Lambda doesn't do WSGI without zappa.

**Comment by jtslear** [comment]
Excellent info.  Thanks for the clarification.  Have a good one.
