### ISSUE TITLE
Ask crash when user user just launch the skill and be quiet

### ISSUE THREAD

**Issue by kienpham2000** [johnwheeler/flask-ask#88]
When user say: Alexa, open XYZ. 
Then Alexa open that skill and playing the welcome text and welcome re-prompt. After that Alexa will send the end session if user doesn't say anything. 

The `@ask.session_ended` decorator never get triggered for me but throwing the following stack 

```
$ python app.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [19/Jan/2017 22:56:20] "POST / HTTP/1.1" 200 -
[2017-01-19 22:56:40,640] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/env27/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/env27/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env27/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env27/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env27/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/env27/src/flask-ask/flask_ask/core.py", line 540, in _flask_view_func
    self._update_stream()
  File "/env27/src/flask-ask/flask_ask/core.py", line 509, in _update_stream
    fresh_stream.__dict__.update(self._from_context())
TypeError: 'NoneType' object is not iterable
```

**Comment by jfmyers** [comment]
I'm experiencing the exact same issue. Has there been any update here?

**Comment by strunker** [comment]
Hi all,

Until this is fixed in the latest version you can do the following. (if you are using pip)

pip uninstall flask-ask (answer yes)

pip install flask-ask==0.8.2

This problem isnt in the 0.8.2 release.

**Comment by johnwheeler** [comment]
@treethought - Based on @strunker's comment, I'm wondering if the removal of this line

https://github.com/johnwheeler/flask-ask/commit/00d88cf367752c8e50ff304fc3830f53db439eeb#diff-9198bf93e3b6758ba586f756ebd51f0fL470

might have something to do with session_ended request no longer working?

**Comment by treethought** [comment]
I think @kiempam2000's PR should fix it. It seems like the context is lost with the session ended request.

**Comment by kienpham2000** [comment]
yea this lib needs a lot of help. Trying to submit my first skill to prod and Alexa team failed me like 5 times already due to various bugs.

**Comment by johnwheeler** [comment]
@treethought does the removal of the prior line of code seem like it would've been causing this? if that's the case, kien's PR looks like a stopgap measure, and I'm hesitant to merge it. are you able to provide more context around what's going on? if not, i can investigate when i have time.

**Comment by kienpham2000** [comment]
@johnwheeler the problem is here: https://github.com/johnwheeler/flask-ask/blob/master/flask_ask/core.py#L532 . 

self.context get set to None under some weird condition.

**Comment by johnwheeler** [comment]
i'm aware of that. we removed a similar line of code which is in my prior comment.

**Comment by treethought** [comment]
@johnwheeler I don't think it was the removal of the code causing the
error. It seems that the session ended request with a 'too many rerompts'
error message is causing the context or some other value to be assigned as
None but I'm not positive. I should be able to look into it in about an
hour or so and get back to you.

**Comment by johnwheeler** [comment]
treethought - no don't worry about it. i just wanted to check with you and get your thoughts. i'll take a look at the pr better and why this might be happening when i can. until then, i'd advise people to downgrade to 0.8.2 which reportedly works

**Comment by treethought** [comment]
Sounds good. I'll still take a look. It's interesting that this appears to
only happen when the reprompt is not answered, but not for other on session
ended situations.

**Comment by strunker** [comment]
Hi all, 
I just wanted to clarify a bit the behavior I am seeing in my case with this. 

It never looks like the code enters the session_ended function. You can allow the reprompt timer to expire, but you can also say "exit" to the skill and force a "user initiated" close. In my case I saw the same behavior when allowing the timer to expire, and when trying to manually exit the skill. 

I know this because I inserted a log into the session_ended function and it is never printed to screen.  

@ask.session_ended
def session_ended():
    log.debug("\n\nHit closing event handler\n\n")
    return statement("")


So what I tried to do then was kind of over ride the Exit keyword with my own exit function. I then setup an utterance to call this new ExitIntent when I say the word 'cancel'.

 @ask.intent("ExitIntent")
 def exit_code():
     log.debug("\n\nHit Exit Intent!!!!\n\n")
     session_ended()


This way I could see how it behaves. And that had a similar effect. The strange part was when calling the session_ended function through my own exit intent function, I actually saw both debug statements print (the one in my exitintent, and the one in the sessionended intent) but I received the same NoneType object is not iterable message. 

Below is a sample error when forcing a user initiated exit, not allowing the reprompt timer to expire.


127.0.0.1 - - [22/Jan/2017 10:32:09] "POST / HTTP/1.1" 200 -
{
  "context": {
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.d452c174-9c70-4f58-951f-422f09bbac58"
      },
      "device": {
        "supportedInterfaces": {
          "AudioPlayer": {}
        }
      },
      "user": {
        "userId": "amzn1.ask.account.AGMOPOZPG2BAPZGJFAR3KTEI6F245ESAPISDS76CSFFLBI76KZPWMCQNS6Q3VXZXSD6JGUU7736MQYH4XFMHRL2B2YKDOBZRWFU4TRBFY5OZOZHORNUVZH4SP3MBVMLE3SD34NRTJA4T7RSEZPMP5EJLRZEEQK4SIVKN6UUW5TDOYP7B3I7WH7EGJ54QKOVTT4APZO5YKYYHYVI"
      }
    }
  },
  "request": {
    "locale": "en-US",
    "reason": "USER_INITIATED",
    "requestId": "amzn1.echo-api.request.7d673e5d-8f8c-48ec-a07e-1a64adad67aa",
    "timestamp": "2017-01-22T15:32:12Z",
    "type": "SessionEndedRequest"
  },
  "session": {
    "application": {
      "applicationId": "amzn1.ask.skill.d452c174-9c70-4f58-951f-422f09bbac58"
    },
    "new": false,
    "sessionId": "amzn1.echo-api.session.ddcb8efd-378d-43f2-bc91-c51724aa78e1",
    "user": {
      "userId": "amzn1.ask.account.AGMOPOZPG2BAPZGJFAR3KTEI6F245ESAPISDS76CSFFLBI76KZPWMCQNS6Q3VXZXSD6JGUU7736MQYH4XFMHRL2B2YKDOBZRWFU4TRBFY5OZOZHORNUVZH4SP3MBVMLE3SD34NRTJA4T7RSEZPMP5EJLRZEEQK4SIVKN6UUW5TDOYP7B3I7WH7EGJ54QKOVTT4APZO5YKYYHYVI"
    }
  },
  "version": "1.0"
}
{
  "context": {
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.d452c174-9c70-4f58-951f-422f09bbac58"
      },
      "device": {
        "supportedInterfaces": {
          "AudioPlayer": {}
        }
      },
      "user": {
        "userId": "amzn1.ask.account.AGMOPOZPG2BAPZGJFAR3KTEI6F245ESAPISDS76CSFFLBI76KZPWMCQNS6Q3VXZXSD6JGUU7736MQYH4XFMHRL2B2YKDOBZRWFU4TRBFY5OZOZHORNUVZH4SP3MBVMLE3SD34NRTJA4T7RSEZPMP5EJLRZEEQK4SIVKN6UUW5TDOYP7B3I7WH7EGJ54QKOVTT4APZO5YKYYHYVI"
      }
    }
  },
  "request": {
    "locale": "en-US",
    "reason": "USER_INITIATED",
    "requestId": "amzn1.echo-api.request.7d673e5d-8f8c-48ec-a07e-1a64adad67aa",
    "timestamp": "2017-01-22T15:32:12Z",
    "type": "SessionEndedRequest"
  },
  "session": {
    "application": {
      "applicationId": "amzn1.ask.skill.d452c174-9c70-4f58-951f-422f09bbac58"
    },
    "new": false,
    "sessionId": "amzn1.echo-api.session.ddcb8efd-378d-43f2-bc91-c51724aa78e1",
    "user": {
      "userId": "amzn1.ask.account.AGMOPOZPG2BAPZGJFAR3KTEI6F245ESAPISDS76CSFFLBI76KZPWMCQNS6Q3VXZXSD6JGUU7736MQYH4XFMHRL2B2YKDOBZRWFU4TRBFY5OZOZHORNUVZH4SP3MBVMLE3SD34NRTJA4T7RSEZPMP5EJLRZEEQK4SIVKN6UUW5TDOYP7B3I7WH7EGJ54QKOVTT4APZO5YKYYHYVI"
    }
  },
  "version": "1.0"
}
127.0.0.1 - - [22/Jan/2017 10:32:14] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\lib\site-packages\flask_ask\core.py", line 544, in _flask_view_func
    self._update_stream()
  File "C:\Python27\lib\site-packages\flask_ask\core.py", line 513, in _update_stream
    fresh_stream.__dict__.update(self._from_context())
TypeError: 'NoneType' object is not iterable

**Comment by johnwheeler** [comment]
very much appreciate this thorough diagnosis @strunker. I skimmed it, and I don't have time to go over this in detail tonight, but we'll get to the bottom of it and get solid fixes out soon. good teamwork

**Comment by treethought** [comment]
Awesome, thanks for the info @strunker
